// Generated by listennotes/devtools/api-sdks/sync.py dotnet. Do not edit.
namespace PodcastAPI;

public sealed partial class Client
{
    // Full-text search (GET /search)
    public Task<ApiResponse> Search(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/search", HttpMethod.Get,
            new string[] {  }, new string[] { "q", "sort_by_date", "type", "offset", "len_min", "len_max", "episode_count_min", "episode_count_max", "update_freq_min", "update_freq_max", "genre_ids", "published_before", "published_after", "only_in", "language", "region", "ocid", "ncid", "safe_mode", "unique_podcasts", "interviews_only", "sponsored_only", "page_size" }, parameters, cancellationToken);

    // Typeahead search (GET /typeahead)
    public Task<ApiResponse> Typeahead(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/typeahead", HttpMethod.Get,
            new string[] {  }, new string[] { "q", "show_podcasts", "show_genres", "safe_mode" }, parameters, cancellationToken);

    // Find individual episodes by searching for their titles (GET /search_episode_titles)
    public Task<ApiResponse> SearchEpisodeTitles(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/search_episode_titles", HttpMethod.Get,
            new string[] {  }, new string[] { "q", "podcast_id", "podcast_id_type" }, parameters, cancellationToken);

    // Spell check on a search term (GET /spellcheck)
    public Task<ApiResponse> SpellCheck(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/spellcheck", HttpMethod.Get,
            new string[] {  }, new string[] { "q" }, parameters, cancellationToken);

    // Fetch related search terms (GET /related_searches)
    public Task<ApiResponse> FetchRelatedSearches(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/related_searches", HttpMethod.Get,
            new string[] {  }, new string[] { "q" }, parameters, cancellationToken);

    // Fetch trending search terms (GET /trending_searches)
    public Task<ApiResponse> FetchTrendingSearches(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/trending_searches", HttpMethod.Get,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Fetch a list of best podcasts by genre (GET /best_podcasts)
    public Task<ApiResponse> FetchBestPodcasts(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/best_podcasts", HttpMethod.Get,
            new string[] {  }, new string[] { "genre_id", "page", "region", "publisher_region", "language", "sort", "safe_mode" }, parameters, cancellationToken);

    // Fetch detailed meta data and episodes for a podcast by id (GET /podcasts/{id})
    public Task<ApiResponse> FetchPodcastById(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts/{id}", HttpMethod.Get,
            new string[] { "id" }, new string[] { "next_episode_pub_date", "sort" }, parameters, cancellationToken);

    // Request to delete a podcast (DELETE /podcasts/{id})
    public Task<ApiResponse> DeletePodcast(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts/{id}", HttpMethod.Delete,
            new string[] { "id" }, new string[] { "reason" }, parameters, cancellationToken);

    // Fetch detailed meta data for an episode by id (GET /episodes/{id})
    public Task<ApiResponse> FetchEpisodeById(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/episodes/{id}", HttpMethod.Get,
            new string[] { "id" }, new string[] { "show_transcript" }, parameters, cancellationToken);

    // Batch fetch basic meta data for episodes (POST /episodes)
    public Task<ApiResponse> BatchFetchEpisodes(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/episodes", HttpMethod.Post,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Batch fetch basic meta data for podcasts (POST /podcasts)
    public Task<ApiResponse> BatchFetchPodcasts(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts", HttpMethod.Post,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Fetch a curated list of podcasts by id (GET /curated_podcasts/{id})
    public Task<ApiResponse> FetchCuratedPodcastsListById(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/curated_podcasts/{id}", HttpMethod.Get,
            new string[] { "id" }, new string[] {  }, parameters, cancellationToken);

    // Fetch a list of podcast genres (GET /genres)
    public Task<ApiResponse> FetchPodcastGenres(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/genres", HttpMethod.Get,
            new string[] {  }, new string[] { "top_level_only" }, parameters, cancellationToken);

    // Fetch a list of supported countries/regions for best podcasts (GET /regions)
    public Task<ApiResponse> FetchPodcastRegions(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/regions", HttpMethod.Get,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Fetch a list of supported languages for podcasts (GET /languages)
    public Task<ApiResponse> FetchPodcastLanguages(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/languages", HttpMethod.Get,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Fetch a random podcast episode (GET /just_listen)
    public Task<ApiResponse> JustListen(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/just_listen", HttpMethod.Get,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Fetch curated lists of podcasts (GET /curated_podcasts)
    public Task<ApiResponse> FetchCuratedPodcastsLists(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/curated_podcasts", HttpMethod.Get,
            new string[] {  }, new string[] { "page" }, parameters, cancellationToken);

    // Fetch recommendations for a podcast (GET /podcasts/{id}/recommendations)
    public Task<ApiResponse> FetchRecommendationsForPodcast(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts/{id}/recommendations", HttpMethod.Get,
            new string[] { "id" }, new string[] { "safe_mode" }, parameters, cancellationToken);

    // Fetch recommendations for an episode (GET /episodes/{id}/recommendations)
    public Task<ApiResponse> FetchRecommendationsForEpisode(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/episodes/{id}/recommendations", HttpMethod.Get,
            new string[] { "id" }, new string[] { "safe_mode" }, parameters, cancellationToken);

    // Submit a podcast to Listen Notes database (POST /podcasts/submit)
    public Task<ApiResponse> SubmitPodcast(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts/submit", HttpMethod.Post,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Fetch a playlist's info and items (i.e., episodes or podcasts). (GET /playlists/{id})
    public Task<ApiResponse> FetchPlaylistById(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists/{id}", HttpMethod.Get,
            new string[] { "id" }, new string[] { "type", "last_timestamp_ms", "sort" }, parameters, cancellationToken);

    // Fetch a list of your playlists. (GET /playlists)
    public Task<ApiResponse> FetchMyPlaylists(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists", HttpMethod.Get,
            new string[] {  }, new string[] { "sort", "page" }, parameters, cancellationToken);

    // Fetch audience demographics for a podcast (GET /podcasts/{id}/audience)
    public Task<ApiResponse> FetchAudienceForPodcast(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts/{id}/audience", HttpMethod.Get,
            new string[] { "id" }, new string[] {  }, parameters, cancellationToken);

    // Fetch podcasts by a publisher's domain name (GET /podcasts/domains/{domain_name})
    public Task<ApiResponse> FetchPodcastsByDomain(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/podcasts/domains/{domain_name}", HttpMethod.Get,
            new string[] { "domain_name" }, new string[] { "page" }, parameters, cancellationToken);

    // Create a playlist. (POST /playlists)
    public Task<ApiResponse> CreatePlaylist(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists", HttpMethod.Post,
            new string[] {  }, new string[] {  }, parameters, cancellationToken);

    // Update playlist metadata. (PUT /playlists/{id})
    public Task<ApiResponse> UpdatePlaylist(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists/{id}", HttpMethod.Put,
            new string[] { "id" }, new string[] {  }, parameters, cancellationToken);

    // Delete a playlist. (DELETE /playlists/{id})
    public Task<ApiResponse> DeletePlaylist(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists/{id}", HttpMethod.Delete,
            new string[] { "id" }, new string[] {  }, parameters, cancellationToken);

    // Add an episode or podcast to a playlist. (POST /playlists/{id}/items)
    public Task<ApiResponse> AddPlaylistItem(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists/{id}/items", HttpMethod.Post,
            new string[] { "id" }, new string[] {  }, parameters, cancellationToken);

    // Remove an item from a playlist. (DELETE /playlists/{id}/items/{item_id})
    public Task<ApiResponse> DeletePlaylistItem(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists/{id}/items/{item_id}", HttpMethod.Delete,
            new string[] { "id", "item_id" }, new string[] {  }, parameters, cancellationToken);

    // Update notes for a playlist item. (PUT /playlists/{id}/items/{item_id})
    public Task<ApiResponse> UpdatePlaylistItemNotes(IDictionary<string, string>? parameters = null,
        CancellationToken cancellationToken = default) =>
        Request("/playlists/{id}/items/{item_id}", HttpMethod.Put,
            new string[] { "id", "item_id" }, new string[] {  }, parameters, cancellationToken);

}
