// Generated by listennotes/devtools/api-sdks/sync.py dotnet. Do not edit.
namespace PodcastAPI.Tests;

internal static class MethodDispatch
{
    public static Task<ApiResponse> Call(string operation, Client client,
        IDictionary<string, string> parameters, CancellationToken token = default) => operation switch
    {
        "search" => client.Search(parameters, token),
        "typeahead" => client.Typeahead(parameters, token),
        "searchEpisodeTitles" => client.SearchEpisodeTitles(parameters, token),
        "spellcheck" => client.SpellCheck(parameters, token),
        "getRelatedSearches" => client.FetchRelatedSearches(parameters, token),
        "getTrendingSearches" => client.FetchTrendingSearches(parameters, token),
        "getBestPodcasts" => client.FetchBestPodcasts(parameters, token),
        "getPodcastById" => client.FetchPodcastById(parameters, token),
        "deletePodcastById" => client.DeletePodcast(parameters, token),
        "getEpisodeById" => client.FetchEpisodeById(parameters, token),
        "getEpisodesInBatch" => client.BatchFetchEpisodes(parameters, token),
        "getPodcastsInBatch" => client.BatchFetchPodcasts(parameters, token),
        "getCuratedPodcastById" => client.FetchCuratedPodcastsListById(parameters, token),
        "getGenres" => client.FetchPodcastGenres(parameters, token),
        "getRegions" => client.FetchPodcastRegions(parameters, token),
        "getLanguages" => client.FetchPodcastLanguages(parameters, token),
        "justListen" => client.JustListen(parameters, token),
        "getCuratedPodcasts" => client.FetchCuratedPodcastsLists(parameters, token),
        "getPodcastRecommendations" => client.FetchRecommendationsForPodcast(parameters, token),
        "getEpisodeRecommendations" => client.FetchRecommendationsForEpisode(parameters, token),
        "submitPodcast" => client.SubmitPodcast(parameters, token),
        "getPlaylistById" => client.FetchPlaylistById(parameters, token),
        "getPlaylists" => client.FetchMyPlaylists(parameters, token),
        "getPodcastAudience" => client.FetchAudienceForPodcast(parameters, token),
        "getPodcastsByDomainName" => client.FetchPodcastsByDomain(parameters, token),
        "createPlaylist" => client.CreatePlaylist(parameters, token),
        "updatePlaylist" => client.UpdatePlaylist(parameters, token),
        "addPlaylistItem" => client.AddPlaylistItem(parameters, token),
        "deletePlaylistItem" => client.DeletePlaylistItem(parameters, token),
        "updatePlaylistItemNotes" => client.UpdatePlaylistItemNotes(parameters, token),
        _ => throw new ArgumentException("Unknown operation", nameof(operation)),
    };
}
