// Generated by listennotes/devtools/api-sdks/sync.py dotnet. Do not edit.
// Compile the README examples without executing requests.
internal static class GeneratedExamples
{
    public static async Task Search()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["q"] = "star wars",
            ["sort_by_date"] = "0",
            ["type"] = "episode",
            ["offset"] = "0",
            ["len_min"] = "10",
            ["len_max"] = "30",
            ["genre_ids"] = "68,82",
            ["published_before"] = "1580172454000",
            ["published_after"] = "0",
            ["only_in"] = "title,description",
            ["language"] = "English",
            ["region"] = "",
            ["safe_mode"] = "0",
            ["unique_podcasts"] = "0",
            ["interviews_only"] = "0",
            ["sponsored_only"] = "0",
            ["page_size"] = "10",
        };
        var response = await client.Search(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task Typeahead()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["q"] = "star wars",
            ["show_podcasts"] = "1",
            ["show_genres"] = "1",
            ["safe_mode"] = "0",
        };
        var response = await client.Typeahead(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task SearchEpisodeTitles()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["q"] = "Jerusalem Demsas on The Dispossessed",
        };
        var response = await client.SearchEpisodeTitles(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task SpellCheck()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["q"] = "microsft stock",
        };
        var response = await client.SpellCheck(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchRelatedSearches()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["q"] = "evergrande",
        };
        var response = await client.FetchRelatedSearches(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchTrendingSearches()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
        };
        var response = await client.FetchTrendingSearches(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchBestPodcasts()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["genre_id"] = "93",
            ["page"] = "2",
            ["region"] = "us",
            ["sort"] = "listen_score",
            ["safe_mode"] = "0",
        };
        var response = await client.FetchBestPodcasts(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchPodcastById()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "4d3fe717742d4963a85562e9f84d8c79",
            ["next_episode_pub_date"] = "1479154463000",
            ["sort"] = "recent_first",
        };
        var response = await client.FetchPodcastById(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task DeletePodcast()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "4d3fe717742d4963a85562e9f84d8c79",
            ["reason"] = "the podcaster wants to delete it",
        };
        var response = await client.DeletePodcast(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchEpisodeById()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "6b6d65930c5a4f71b254465871fed370",
            ["show_transcript"] = "1",
        };
        var response = await client.FetchEpisodeById(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task BatchFetchEpisodes()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["ids"] = "c577d55b2b2b483c969fae3ceb58e362,0f34a9099579490993eec9e8c8cebb82",
        };
        var response = await client.BatchFetchEpisodes(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task BatchFetchPodcasts()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["ids"] = "3302bc71139541baa46ecb27dbf6071a,68faf62be97149c280ebcc25178aa731,37589a3e121e40debe4cef3d9638932a,9cf19c590ff0484d97b18b329fed0c6a",
            ["rsses"] = "https://rss.art19.com/recode-decode,https://rss.art19.com/the-daily,https://www.npr.org/rss/podcast.php?id=510331,https://www.npr.org/rss/podcast.php?id=510331",
            ["itunes_ids"] = "1457514703,1386234384,659155419",
            ["spotify_ids"] = "3DDfEsKDIDrTlnPOiG4ZF4,4qDNe5Gvl1XxdLinUGEXrC,23NZCM4ik6o3UYkM473Itz",
            ["show_latest_episodes"] = "1",
            ["next_episode_pub_date"] = "1557394247000",
        };
        var response = await client.BatchFetchPodcasts(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchCuratedPodcastsListById()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "SDFKduyJ47r",
        };
        var response = await client.FetchCuratedPodcastsListById(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchPodcastGenres()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["top_level_only"] = "1",
        };
        var response = await client.FetchPodcastGenres(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchPodcastRegions()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
        };
        var response = await client.FetchPodcastRegions(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchPodcastLanguages()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
        };
        var response = await client.FetchPodcastLanguages(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task JustListen()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
        };
        var response = await client.JustListen(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchCuratedPodcastsLists()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["page"] = "2",
        };
        var response = await client.FetchCuratedPodcastsLists(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchRecommendationsForPodcast()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "25212ac3c53240a880dd5032e547047b",
            ["safe_mode"] = "0",
        };
        var response = await client.FetchRecommendationsForPodcast(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchRecommendationsForEpisode()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "254444fa6cf64a43a95292a70eb6869b",
            ["safe_mode"] = "0",
        };
        var response = await client.FetchRecommendationsForEpisode(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task SubmitPodcast()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["rss"] = "https://feeds.megaphone.fm/committed",
            ["email"] = "hello@example.com",
        };
        var response = await client.SubmitPodcast(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchPlaylistById()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "m1pe7z60bsw",
            ["type"] = "episode_list",
            ["last_timestamp_ms"] = "0",
            ["sort"] = "recent_added_first",
        };
        var response = await client.FetchPlaylistById(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchMyPlaylists()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["sort"] = "recent_added_first",
            ["page"] = "1",
        };
        var response = await client.FetchMyPlaylists(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchAudienceForPodcast()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "25212ac3c53240a880dd5032e547047b",
        };
        var response = await client.FetchAudienceForPodcast(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task FetchPodcastsByDomain()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["domain_name"] = "nytimes.com",
            ["page"] = "1",
        };
        var response = await client.FetchPodcastsByDomain(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task CreatePlaylist()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["name"] = "My favorite podcasts",
            ["description"] = "Podcasts and episodes to revisit.",
            ["visibility"] = "public",
            ["type"] = "episode_list",
        };
        var response = await client.CreatePlaylist(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task UpdatePlaylist()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "m1pe7z60bsw",
            ["name"] = "My favorite podcasts",
            ["description"] = "Podcasts and episodes to revisit.",
            ["visibility"] = "public",
            ["type"] = "podcast_list",
        };
        var response = await client.UpdatePlaylist(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task DeletePlaylist()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "m1pe7z60bsw",
        };
        var response = await client.DeletePlaylist(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task AddPlaylistItem()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "m1pe7z60bsw",
            ["episode_id"] = "e53e6992a5b7492f9ea6fcd85d9ad95f",
            ["notes"] = "Worth a listen.",
        };
        var response = await client.AddPlaylistItem(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task DeletePlaylistItem()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "m1pe7z60bsw",
            ["item_id"] = "23",
        };
        var response = await client.DeletePlaylistItem(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

    public static async Task UpdatePlaylistItemNotes()
    {
        using var client = new PodcastAPI.Client(Environment.GetEnvironmentVariable("LISTEN_API_KEY"));
        var parameters = new Dictionary<string, string>
        {
            ["id"] = "m1pe7z60bsw",
            ["item_id"] = "23",
            ["notes"] = "",
        };
        var response = await client.UpdatePlaylistItemNotes(parameters);
        Console.WriteLine(response.ToJSON<dynamic>());
    }

}
